spring:
  profiles:
    active: default

  application:
    name: auth-service

  jwt:
    secret: testSecretKey

    token:
      access-expiration-time: 3600000
      refresh-expiration-time: 86400000

  config:
    import: optional:configserver:http://localhost:9000

  cloud:
    config:
      label: main