spring:
  profiles:
    active: default

  application:
    name: auth-service

  jwt:
    secret: testSecretKey

    token:
      access-expiration-time: 3600000
      refresh-expiration-time: 86400000

  config:
    import: optional:configserver:http://localhost:9000

  cloud:
    config:
      label: main

gateway:
  url: http://localhost:8000

---
spring:
  config:
    activate:
      on-profile: live

    import: optional:configserver:http://55g-config-live:9000

---
spring:
  config:
    activate:
      on-profile: dev

    import: optional:configserver:http://55g-config-dev:9050