spring:
  profiles:
    active: default

  application:
    name: auth-service

  jwt:
    secret: badfgkamsdgokmgweogsmaodgaoeirmgiofmdklhdfhhasfahdfvgohmeoagdfgmfomha

    token:
      access-expiration-time: 600000
      refresh-expiration-time: 1200000

  config:
    import: optional:configserver:http://localhost:9000

  cloud:
    config:
      label: main

  rabbitmq:
    host: host
    port: 0
    username: username
    password: password

gateway:
  url: http://localhost:8000

redis:
  host: host
  port: 0
  password: password

---
spring:
  config:
    activate:
      on-profile: live

    import: optional:configserver:http://55g-config-live:9000

---
spring:
  config:
    activate:
      on-profile: dev

    import: optional:configserver:http://55g-config-dev:9050